const cartTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    REDUCE_CART_ITEM: 'REDUCE_CART_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    ADD_QTY_ITEM: 'ADD_QTY_ITEM',
    MINUS_QTY_ITEM: 'MINUS_QTY_ITEM',

};

export default cartTypes;