const productsTypes = {
    ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT: 'SET_PRODUCT',
    DELETE_PRODUCTS_START: 'DELETE_PRODUCTS_START',
    FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
    
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
};


export const ADD_NEW_PRODUCT_START = 'ADD_NEW_PRODUCT_START';
export const DELETE_PRODUCTS_START = 'DELETE_PRODUCTS_START';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';


export default productsTypes;